export const LEAGUES = {
  ESP: 'ESP',
  ENG: 'ENG',
  GER: 'GER',
  ITA: 'ITA',
  INT: 'INT',
  POR: 'POR',
  RUS: 'RUS',
  TUR: 'TUR',

}

export const TEAMS = [
  {name: 'Real Madrid', league: LEAGUES.ESP, stars: 10},
  {name: 'Barcelona', league: LEAGUES.ESP, stars: 10},
  {name: 'Atletico Madrid', league: LEAGUES.ESP, stars: 10},
  {name: 'Athletic Bilbao', league: LEAGUES.ESP, stars: 9},
  {name: 'Real Sociedad', league: LEAGUES.ESP, stars: 9},
  {name: 'Sevilla FC', league: LEAGUES.ESP, stars: 9},
  {name: 'Valencia CF', league: LEAGUES.ESP, stars: 9},
  {name: 'Villarreal CF', league: LEAGUES.ESP, stars: 9},
  {name: 'Fenerbahçe', league: LEAGUES.TUR, stars: 9},
  {name: 'Besiktas', league: LEAGUES.TUR, stars: 9},
  {name: 'Galatasaray', league: LEAGUES.TUR, stars: 9},
  {name: 'Arsenal', league: LEAGUES.ENG, stars: 10},
  {name: 'Chelsea', league: LEAGUES.ENG, stars: 10},
  {name: 'Everton', league: LEAGUES.ENG, stars: 9},
  {name: 'Liverpool', league: LEAGUES.ENG, stars: 9},
  {name: 'Manchester City', league: LEAGUES.ENG, stars: 10},
  {name: 'Manchester United', league: LEAGUES.ENG, stars: 10},
  {name: 'Southampton', league: LEAGUES.ENG, stars: 9},
  {name: 'Spurs', league: LEAGUES.ENG, stars: 9},
  {name: 'Swansea City', league: LEAGUES.ENG, stars: 10},
  {name: 'Paris Saint-Germain', league: LEAGUES.FRA, stars: 10},
  {name: 'Monaco', league: LEAGUES.FRA, stars: 9},
  {name: 'Bayer 04', league: LEAGUES.GER, stars: 9},
  {name: 'Dortmund', league: LEAGUES.GER, stars: 10},
  {name: 'Bor. M’gladbach', league: LEAGUES.GER, stars: 9},
  {name: 'FC Bayern', league: LEAGUES.GER, stars: 10},
  {name: 'FC Schalke', league: LEAGUES.GER, stars: 10},
  {name: 'VfL Wolfsburg', league: LEAGUES.GER, stars: 10},
  {name: 'Argentina', league: LEAGUES.INT, stars: 10},
  {name: 'Belgium', league: LEAGUES.INT, stars: 10},
  {name: 'Brazil', league: LEAGUES.INT, stars: 10},
  {name: 'Columbia', league: LEAGUES.INT, stars: 9},
  {name: 'England', league: LEAGUES.INT, stars: 10},
  {name: 'France', league: LEAGUES.INT, stars: 10},
  {name: 'Germany', league: LEAGUES.INT, stars: 10},
  {name: 'Italy', league: LEAGUES.INT, stars: 10},
  {name: 'Netherlands', league: LEAGUES.INT, stars: 10},
  {name: 'Portugal', league: LEAGUES.INT, stars: 10},
  {name: 'Russia', league: LEAGUES.INT, stars: 9},
  {name: 'Spain', league: LEAGUES.INT, stars: 10},
  {name: 'Switzerland', league: LEAGUES.INT, stars: 9},
  {name: 'Turkey', league: LEAGUES.INT, stars: 9},
  {name: 'Uruguay', league: LEAGUES.INT, stars: 9},
  {name: 'Fiorentina', league: LEAGUES.ITA, stars: 9},
  {name: 'Inter', league: LEAGUES.ITA, stars: 9},
  {name: 'Juventus', league: LEAGUES.ITA, stars: 10},
  {name: 'Lazio', league: LEAGUES.ITA, stars: 9},
  {name: 'AC Milan', league: LEAGUES.ITA, stars: 9},
  {name: 'Napoli', league: LEAGUES.ITA, stars: 9},
  {name: 'Roma', league: LEAGUES.ITA, stars: 9},
  {name: 'FC Porto', league: LEAGUES.POR, stars: 9},
  {name: 'SL Benefica', league: LEAGUES.POR, stars: 9},
  {name: 'Sporting', league: LEAGUES.POR, stars: 9},
  {name: 'CSKA Moskva', league: LEAGUES.RUS, stars: 9},
  {name: 'Zenit', league: LEAGUES.RUS, stars: 9},
]